//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Player.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Player : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Player()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player"",
    ""maps"": [
        {
            ""name"": ""Movimiento"",
            ""id"": ""09d00517-9806-4a24-9d40-7c7dc694e7d4"",
            ""actions"": [
                {
                    ""name"": ""MovimientoHorizontal"",
                    ""type"": ""Value"",
                    ""id"": ""01a428b1-15ee-4b82-a9ff-ace5d3c2ea6b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MovimientoVertical"",
                    ""type"": ""Button"",
                    ""id"": ""2a969650-d95e-4a38-82bc-cf6225133e61"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Horizontal"",
                    ""id"": ""d612fb1a-fb01-4563-bc62-e3f988c75657"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovimientoHorizontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""a8054c45-748f-49dd-92e0-ab70b244dac6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovimientoHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""75884ec9-4c7d-4ac2-9f4a-0c3dd6efa977"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovimientoHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""HorizontalControl"",
                    ""id"": ""7048d339-650f-47e8-bcc0-0bbd46c7ba58"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovimientoHorizontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""61d5c2a7-ff86-4eac-98c2-6dcc111f1572"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovimientoHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""de725d33-0ac7-4636-824c-e62f2e8db98c"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovimientoHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Vertical"",
                    ""id"": ""2411cc50-f58e-4543-b0f2-bc7e44a36af1"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovimientoVertical"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""031d4137-0387-4d52-8ec3-e2cbd9840682"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovimientoVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""3e223d8d-c1f3-4387-ae20-60fadd1315b3"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovimientoVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Movimiento
        m_Movimiento = asset.FindActionMap("Movimiento", throwIfNotFound: true);
        m_Movimiento_MovimientoHorizontal = m_Movimiento.FindAction("MovimientoHorizontal", throwIfNotFound: true);
        m_Movimiento_MovimientoVertical = m_Movimiento.FindAction("MovimientoVertical", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Movimiento
    private readonly InputActionMap m_Movimiento;
    private IMovimientoActions m_MovimientoActionsCallbackInterface;
    private readonly InputAction m_Movimiento_MovimientoHorizontal;
    private readonly InputAction m_Movimiento_MovimientoVertical;
    public struct MovimientoActions
    {
        private @Player m_Wrapper;
        public MovimientoActions(@Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @MovimientoHorizontal => m_Wrapper.m_Movimiento_MovimientoHorizontal;
        public InputAction @MovimientoVertical => m_Wrapper.m_Movimiento_MovimientoVertical;
        public InputActionMap Get() { return m_Wrapper.m_Movimiento; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MovimientoActions set) { return set.Get(); }
        public void SetCallbacks(IMovimientoActions instance)
        {
            if (m_Wrapper.m_MovimientoActionsCallbackInterface != null)
            {
                @MovimientoHorizontal.started -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnMovimientoHorizontal;
                @MovimientoHorizontal.performed -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnMovimientoHorizontal;
                @MovimientoHorizontal.canceled -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnMovimientoHorizontal;
                @MovimientoVertical.started -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnMovimientoVertical;
                @MovimientoVertical.performed -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnMovimientoVertical;
                @MovimientoVertical.canceled -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnMovimientoVertical;
            }
            m_Wrapper.m_MovimientoActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MovimientoHorizontal.started += instance.OnMovimientoHorizontal;
                @MovimientoHorizontal.performed += instance.OnMovimientoHorizontal;
                @MovimientoHorizontal.canceled += instance.OnMovimientoHorizontal;
                @MovimientoVertical.started += instance.OnMovimientoVertical;
                @MovimientoVertical.performed += instance.OnMovimientoVertical;
                @MovimientoVertical.canceled += instance.OnMovimientoVertical;
            }
        }
    }
    public MovimientoActions @Movimiento => new MovimientoActions(this);
    public interface IMovimientoActions
    {
        void OnMovimientoHorizontal(InputAction.CallbackContext context);
        void OnMovimientoVertical(InputAction.CallbackContext context);
    }
}
